### ISSUE TITLE
Link to Schema plugin repository doesn't get latest changes

### ISSUE THREAD

**Issue by milleri** [geonetwork-delwp/metashare#22]
The link in the schemas directory is to "iso19115-3 @ d2031b5" which seems to be a snapshot of the iso19115-3 repo.  This means when I do a git pull on metar, I don't get the updated schema.
Is this intended?  
At present I have an inconsistency between the metadata  genrated by metar and what GeoNetwork expects - in particular for urn:delwp:metashare:license:delwpdatalicense which is in the metadata but I don;'t think is in the latest schema.

**Comment by sppigot** [comment]
Ian, Not intentional but likely not the issue as the schema plugin is really only used by the metar tools to get the schema xsds for validation and these haven't changed for quite a while. I think the problem you are seeing is caused by a missing subtemplate/fragment of XML that describes this license - these need to be loaded via the admin interface Admin Console>Metadata & Templates - load the templates for the DELWP profile.

**Comment by milleri** [comment]
I reloaded the DELWP profile templates, thanks.  This actually fixed the problem we were having with editing, however it did not fix the original issue with urn:delwp:metashare:license:delwpdatalicense.
I have done some further investigation and I think the problem is that in binding.xml, line 469, the following is configured:
          <value name='href' ns="http://www.w3.org/1999/xlink" constant="local://srv/api/registries/entries/urn:delwp:metashare:license:delwpdatalicense"/>

but the schema template, in sub-delwp-license.xml defines:
uuid="urn:delwp:metashare:delwpdatalicense"

i.e.  there is an additional "license" in the urn in the metashare metar binding.xml.

**Comment by sppigot** [comment]
Ian - actually the details of the urn are "urn:delwp:<metashare|rastermeta>:<type of fragment>:<identifier>

type of fragment can be license|sensor|contact

so the fragment (subtemplate) has the wrong urn. I have fixed it. You will need to reload the templates again and delete the fragment with the wrong urn (Directories interface).
